### PR TITLE
Convert commands to use user attributes

### LINKED ISSUE #83: Replace preprocessor commands with user attributes
It feels like it would be better for ZEROS, RAND, and URL to be handled via user attributes attached to the objects they initialize. That way they can use completions, constants, etc. I'd also like CALL to work this way, which I suppose would be attached to the main entrypoint.

### PR DESCRIPTION
**Pull request by Devon7925**
fixes #83

- [x] URL
- [x] ZEROS
- [x] RAND

Choices:
* Added `BLACK` attribute to replace `ZEROS` for textures
* `ZEROS` and `RAND` are always 1D now since you can multiply constants to get prior behavior

### CODE REVIEW

**Comment by Devon7925** [comment]
I chose to remove `CALL` from scope for now since it relies on better `WASM` support for the reflection API. I also think `CALL` might not be the best way to serve its functionality. I would like a solution that covers some more use cases such as running on init or running based on a runtime dynamic size.

**Review by csyonghe — APPROVED** [review]

**Comment by csyonghe** [comment]
Have we tested all the existing examples?

**Comment by Devon7925** [comment]
Yes. Branch deploy is here https://devon7925.github.io/slang-playground/ if you want to try yourself.

**Comment by csyonghe** [comment]
Thank you, looks great!

**Pull request merged**
